In [1]:
import pandas as pd

In [ ]:
input_b = pd.read_csv("in/CC22_1_ds_e1.0_k2.csv")
# a.to_csv("output.csv", index=False)
type(input_b)
input_b

,GENDER,AGE,RACE,ETHNICITY,encounter_count,num_procedures,num_medications,num_immunizations,num_allergies,num_devices,asthma_flag,stroke_flag,obesity_flag,depression_flag,mean_systolic_bp,mean_diastolic_bp,mean_bmi,mean_weight
0,F,100,white,nonhispanic,71,179,24,13,0,17,0,1,1,0,105.80,66.50,27.40,72.30
1,M,39,white,nonhispanic,29,83,10,11,0,6,0,1,0,0,130.40,100.70,28.14,84.97
2,F,28,white,nonhispanic,29,88,6,9,0,2,0,0,0,0,126.50,67.25,21.72,59.18
3,M,17,white,nonhispanic,25,90,9,18,3,9,0,0,0,0,133.30,76.70,21.86,44.94
4,M,82,white,nonhispanic,36,167,15,13,0,3,0,0,0,0,96.00,76.83,28.10,82.30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,M,80,white,nonhispanic,66,231,5,12,0,4,0,1,0,0,110.95,67.19,27.20,65.00
9996,F,21,white,nonhispanic,93,159,11,17,2,5,0,0,0,0,127.35,69.43,24.07,48.76
9997,M,4,white,nonhispanic,19,20,2,32,0,0,0,0,0,0,108.33,94.33,34.14,10.52
9998,F,59,white,nonhispanic,37,108,9,15,0,6,0,1,1,0,143.54,101.62,27.50,76.20
9999,M,45,white,nonhispanic,12,32,1,7,0,1,0,0,1,0,101.75,78.50,30.70,96.85

In [8]:
input_c = pd.read_csv("in/CC22_1.csv")
# a.to_csv("output.csv", index=False)
type(input_c)
input_c

,GENDER,AGE,RACE,ETHNICITY,encounter_count,num_procedures,num_medications,num_immunizations,num_allergies,num_devices,asthma_flag,stroke_flag,obesity_flag,depression_flag,mean_systolic_bp,mean_diastolic_bp,mean_bmi,mean_weight
0,M,54,white,nonhispanic,39,119,16,11,5,5,0,0,1,0,124.16,88.75,25.83,101.59
1,M,8,white,nonhispanic,28,3,0,34,1,0,0,1,0,0,115.48,88.83,32.13,14.10
2,M,22,white,nonhispanic,51,109,2,12,9,2,0,0,0,1,122.48,85.94,36.86,64.13
3,M,34,white,nonhispanic,15,20,0,5,9,0,0,0,1,0,91.60,74.64,33.06,90.38
4,F,61,white,nonhispanic,769,1001,736,13,2,15,1,1,0,0,120.01,77.65,22.39,76.97
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,M,98,white,nonhispanic,37,248,13,8,2,3,0,1,0,0,119.14,71.75,20.65,74.16
9996,F,64,hawaiian,nonhispanic,40,136,21,15,0,0,0,1,0,0,88.23,72.22,33.29,75.39
9997,M,89,white,hispanic,96,222,69,12,1,5,1,0,0,0,105.69,71.26,25.63,82.04
9998,F,49,white,nonhispanic,34,87,51,15,0,5,0,0,1,0,120.13,72.30,25.41,78.97
9999,M,36,white,nonhispanic,13,25,4,7,1,3,0,1,0,0,106.64,81.48,30.27,87.89

In [ ]:
input_c.columns[0]

Index(['GENDER', 'AGE', 'RACE', 'ETHNICITY', 'encounter_count',
       'num_procedures', 'num_medications', 'num_immunizations',
       'num_allergies', 'num_devices', 'asthma_flag', 'stroke_flag',
       'obesity_flag', 'depression_flag', 'mean_systolic_bp',
       'mean_diastolic_bp', 'mean_bmi', 'mean_weight'],
      dtype='object')

In [24]:
input_c.dtypes

GENDER                object
AGE                    int64
RACE                  object
ETHNICITY             object
encounter_count        int64
num_procedures         int64
num_medications        int64
num_immunizations      int64
num_allergies          int64
num_devices            int64
asthma_flag            int64
stroke_flag            int64
obesity_flag           int64
depression_flag        int64
mean_systolic_bp     float64
mean_diastolic_bp    float64
mean_bmi             float64
mean_weight          float64
dtype: object

In [23]:
input_c.dtypes
for i in input_b.columns:
    input_c[i] = input_c[i].astype(input_b[i].dtype)
input_c

,GENDER,AGE,RACE,ETHNICITY,encounter_count,num_procedures,num_medications,num_immunizations,num_allergies,num_devices,asthma_flag,stroke_flag,obesity_flag,depression_flag,mean_systolic_bp,mean_diastolic_bp,mean_bmi,mean_weight
0,M,61,white,nonhispanic,43,131,23,16,0,40,0,0,1,0,136.735056,72.979810,23.328301,93.621736
1,F,60,other,nonhispanic,124,240,107,11,0,1,0,1,1,0,98.832143,97.334042,27.182177,78.226227
2,F,37,asian,nonhispanic,657,967,1373,22,0,133,1,1,1,1,116.692137,67.321795,49.897074,112.302812
3,F,95,white,nonhispanic,810,647,886,5,0,113,0,1,1,0,96.936061,86.398369,60.469162,111.324872
4,F,5,white,nonhispanic,787,100,17,26,3,49,0,0,0,0,111.299595,85.479466,38.550735,6.899493
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,F,45,other,nonhispanic,56,100,29,10,0,4,0,1,1,0,132.516735,73.871453,56.201653,78.206329
9996,M,82,white,nonhispanic,99,153,58,13,10,58,0,1,0,0,108.703897,75.062901,65.158407,61.417486
9997,M,20,white,nonhispanic,25,193,612,11,0,6,0,1,0,0,132.156469,78.372203,29.713080,91.615407
9998,F,32,native,hispanic,65,1697,1950,33,0,120,0,0,1,1,124.474753,47.251831,31.322002,96.609731
9999,M,16,hawaiian,nonhispanic,40,64,30,15,0,6,0,0,0,0,103.549543,71.087008,36.028341,50.929393